### ISSUE TITLE
앱 실행 오류 : Unhandled Exception: Bad state: Reflectable has not been initialized.

### ISSUE THREAD

**Issue by W1nU** [iamport/iamport_flutter#36]
안녕하세요.

아임포트 결제모듈 연동을 시도하다가 Json Mapper 쪽에서 에러가 있는듯 하여 문의드입니다. 

```
targets:
  $default:
    builders:
      dart_json_mapper:
        generate_for:
          - lib/main.dart

      reflectable:
        generate_for:
          - no/files
```

build.yaml을 다음과 같이 작성하고, initializeJsonMapper를 호출한 뒤 flutter run을 실행하면,

```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Bad state: Reflectable has not been initialized.
Please make sure that the first action taken by your program
in `main` is to call `initializeReflectable()`.
#0      data (package:reflectable/src/reflectable_builder_based.dart:180:5)
#1      data (package:reflectable/src/reflectable_builder_based.dart)
#2      ReflectableImpl.annotatedClasses (package:reflectable/src/reflectable_builder_based.dart:2621:9)
#3      JsonMapper._enumerateAnnotatedClasses (package:dart_json_mapper/src/mapper.dart:457:19)
#4      JsonMapper._updateInternalMaps (package:dart_json_mapper/src/mapper.dart:154:5)
#5      JsonMapper.useAdapter (package:dart_json_mapper/src/mapper.dart:96:5)
#6      new JsonMapper._internal (package:dart_json_mapper/src/mapper.dart:147:5)
#7      JsonMapper.instance (package:dart_json_mapper/src/mapper.dart:114:49)
#8      JsonMapper.instance (package:dart_json_mapper/src/mapper.dart)
#9      new JsonMapper (package:dart_json_mapper/src/mappe<…>
```

에러가 나옵니다. 혹시 보고된 에러라면, 해결법을 알려주시면 감사하겠습니다 :)

**Comment by anymate98** [comment]
안녕하세요, 아임포트 기술지원팀입니다.

혹시 build.yaml 작성 후 `dart run build_runner build` 명령을 실행하셨나요?
에러 메시지를 보면 mapper 파일이 없어서 문제가 발생하는 것으로 보입니다.

**Comment by W1nU** [comment]
넵 해당 명령어 실행하였고, 
`
import 'package:subping/main.mapper.g.dart';`

void main() async {
  initializeJsonMapper();
  WidgetsFlutterBinding.ensureInitialized();
  await GetStorage.init();
  runApp(app());
}
`
처럼 초기화 명령도 실행하였습니다.

**Comment by anymate98** [comment]
해당 문제를 재현할 수가 없습니다.
어떤 라이브러리 버전을 사용하시는지,
또 프로젝트 파일 구조가 어떻게 구성되어있는지도 확인이 필요할 것 같습니다.

**Comment by W1nU** [comment]
```
iamport_flutter:
    dependency: "direct main"
    description:
      name: iamport_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.0-dev.3"
  iamport_webview_flutter:
    dependency: transitive
    description:
      name: iamport_webview_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.3"

  dart_json_mapper:
    dependency: transitive
    description:
      name: dart_json_mapper
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
```

```
root / 
    lib /
        main.dart
        main.mapper.g.dart
   pubspec.yaml
   build.yaml
```

입니다 :)
